### PR TITLE
Update KTLOSSSCLoot.json

### PR DESCRIPTION
**Pull request by shanemcdowell007**
Did Hunter loot.

### CODE REVIEW

**Review by dillmcpickle — CHANGES_REQUESTED** [review]
You should give the helms after the mages to the warlocks, since they dont need set bonuses. only give it to a hunter over a warlock if the hunter already has the other 3 pieces of T5. otherwise the helm will sit in the hunters bags as they cannot break beastlord 4 set.

**Review by shanemcdowell007 — COMMENTED** [review]
I agree with this.

**Review by shanemcdowell007 — COMMENTED** [review]
ok

**Review by shanemcdowell007 — COMMENTED** [review]
changes made.

**Review by dillmcpickle — APPROVED** [review]

**Pull request merged**
